//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZuLuCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLevel
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int LevelId { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
